[package]
name = "rustgenhash"
version = "0.3.1"
license = "MIT/Apache-2.0"
authors = ["Volker Schwaberow <volker@schwaberow.de>"]
description = "A tool to generate hashes from the command line."
homepage = "https://github.com/vschwaberow/rustgenhash"
repository = "https://github.com/vschwaberow/rustgenhash"
readme = "README.md"
keywords = ["cli", "crypto", "hashes", "rust"]
edition = "2018"
categories = [ "command-line-utilities", "cryptography"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["std"]
std = []

[dependencies]
blake2 = "0.9.2"
digest = { version = "0.9.0", features = ["std"] }
md2 = "0.9.0"
md4 = "0.9.0"
md-5 = "0.9.1"
gost94 = "0.9.1"
groestl = "0.9.0"
ripemd160 = "0.9.1"
ripemd320 = "0.9.0"
sha-1 = "0.9.8"
sha2 = "0.9.8"
sha3 = "0.9.1"
shabal = "0.3.0"
streebog = "0.9.2"
structopt = "0.3.23"
structopt-derive = "0.4.16"
whirlpool = "0.9.0"
hex-literal = "0.3.3"
