[package]
name = "rustgenhash"
version = "0.1.7"
license = "MIT/Apache-2.0"
authors = ["Volker Schwaberow <volker@schwaberow.de>"]
description = "A tool to generate hashes from the command line."
homepage = "https://github.com/vschwaberow/rustgenhash"
repository = "https://github.com/vschwaberow/rustgenhash"
readme = "README.md"
keywords = ["cli", "crypto", "hashes", "rust"]
edition = "2018"
categories = [ "command-line-interface", "command-line-utilities", "cryptography"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake2 = "0.9.1"
digest = "0.9.0"
structopt = "0.3.20"
md2 = "0.9.0"
md4 = "0.9.0"
md-5 = "0.9.1"
gost94 = "0.9.0"
ripemd160 = "0.9.1"
sha-1 = "0.9.1"
sha2 = "0.9.1"
sha3 = "0.9.1"
whirlpool = "0.9.0"
