[package]
name = "rustgenhash"
version = "0.1.1"
license-file = "LICENSE"
authors = ["Volker Schwaberow <volker@schwaberow.de>"]
description = "A tool to generate hashes from the command line."
readme = "README.md"
keywords = ["cli", "crypto", "hashes", "rust"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.20"
rust-crypto ="0.2.36"
