[package]
name = "rustgenhash"
version = "0.1.4"
license-file = "LICENSE"
authors = ["Volker Schwaberow <volker@schwaberow.de>"]
description = "A tool to generate hashes from the command line."
readme = "README.md"
keywords = ["cli", "crypto", "hashes", "rust"]
edition = "2018"
categories = [ "command-line-interface", "command-line-utilities", "cryptography"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
digest = "0.9.0"
structopt = "0.3.20"
md-5 = "0.9.1"
ripemd160 = "0.9.1"
sha-1 = "0.9.1"
sha2 = "0.9.1"
sha3 = "0.9.1"
whirlpool = "0.9.0"
