
  # After registering a name on build.snapcraft.io, commit an uncommented line:
  # name: rustgenhash
  name: rustgenhash
  version: '0.3.0' # just for humans, typically '1.2+git' or '1.3.2'
  summary: Generate and check hashes in various algorithms # 79 char long summary
  description: |
    rustgenhash is a tool to generate hashes on the commandline from stdio.It can 
    be used to generate single or multiple hashes for usage in password databases 
    or even in penetration testing scenarios where you want to test password 
    cracking tools.

  grade: stable # must be 'stable' to release into candidate/stable channels
  base: core18
  confinement: strict # use 'strict' once you have the right plugs and slots

  parts:
    rustgenhash:
      # See 'snapcraft plugins'
      plugin: rust
      source: .
      
  apps:
    rustgenhash:
      command: bin/rustgenhash
  
